Use variables in postinst Create index forgotten by Joomla Update TODO

diff --git a/openapp-joomla-1.6.3/debian/postinst b/openapp-joomla-1.6.3/debian/postinst
--- a/openapp-joomla-1.6.3/debian/postinst
+++ b/openapp-joomla-1.6.3/debian/postinst
@@ -29,6 +29,9 @@ install_joomla() {
 	MIRROR=http://www.tuxis.nl/uploads/tmp
 	PASSWORD=`pwgen -s 10`
 
+	MYSQL=/usr/bin/mysql
+	OPTS="--defaults-file=/etc/mysql/debian.cnf"
+
 	echo "Creating backup of current /var/www in /var/backups/var.www.joomla.tgz"
 	tar zcf /var/backups/var.www.joomla.tgz /var/www/
 
@@ -42,9 +45,9 @@ install_joomla() {
 		mkdir -p ${INSTALLDIR} || fatal "Unable to create directory ${INSTALLDIR}"
 		cd ${INSTALLDIR} || fatal "Unable to go into directory ${INSTALLDIR}"
 		tar zxf /tmp/joomla-$$.tar.gz || fatal "Unable to extract Joomla package into ${INSTALLDIR}"
-		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "CREATE DATABASE joomla CHARACTER SET utf8 COLLATE utf8_general_ci;" || fatal "Unable to create database joomla"
-		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "GRANT USAGE ON mysql.* TO 'joomla'@'localhost' IDENTIFIED BY '$PASSWORD';" || fatal "Unable to create mysql-user joomla"
-		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "GRANT ALL PRIVILEGES ON joomla.* to 'joomla'@'localhost';"|| fatal "Unable to set permissions to mysql-user joomla"
+		${MYSQL} ${OPTS} -e "CREATE DATABASE joomla CHARACTER SET utf8 COLLATE utf8_general_ci;" || fatal "Unable to create database joomla"
+		${MYSQL} ${OPTS} -e "GRANT USAGE ON mysql.* TO 'joomla'@'localhost' IDENTIFIED BY '$PASSWORD';" || fatal "Unable to create mysql-user joomla"
+		${MYSQL} ${OPTS} -e "GRANT ALL PRIVILEGES ON joomla.* to 'joomla'@'localhost';"|| fatal "Unable to set permissions to mysql-user joomla"
 		/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf flush-privileges || fatal "Unable to flush mysql privileges"
 
 		mv ${INSTALLDIR}/installation/configuration.php-dist ${INSTALLDIR}/configuration.php.tmp || fatal "Unable to move configuration.php to temporary file"
@@ -53,7 +56,8 @@ install_joomla() {
 		  sed -e "s#\$password = ''#\$password = '${PASSWORD}'#" | \
 		  sed -e "s#\$db = ''#\$db = 'joomla'#" > ${INSTALLDIR}/configuration.php
                 [ $? -eq 0 ] || fatal "Unable to prepare ${INSTALLDIR}/configuration.php"
-		cat ${INSTALLDIR}/installation/sql/mysql/joomla.sql | sed -e 's/#__/jos_/g' | mysql --defaults-file=/etc/mysql/debian.cnf joomla || fatal "Unable to add data to the database"
+		cat ${INSTALLDIR}/installation/sql/mysql/joomla.sql | sed -e 's/#__/jos_/g' | ${MYSQL} joomla || fatal "Unable to add data to the database"
+		${MYSQL} ${OPTS} joomla -e "CREATE INDEX jos_template_styles(client_id);"
 	fi
 	echo "Fixing permissions on /var/www"
 	chown -R www-data:www-data /var/www
