* Add a TODO file (currently empty, but still)   * Restart Apache after install so php actually works after     a fresh install   * Clear /var/www before installing Joomla. We expect only Joomla     in /var/www. But do make a backup of the current /var/www   * Fix permissions on /var/www   * Fix a typo in openapp-joomla-passwd   * Remove ${INSTALLDIR}/configuration.php.tmp after install

diff --git a/openapp-joomla-1.6.3/openapp-joomla-passwd b/openapp-joomla-1.6.3/openapp-joomla-passwd
--- a/openapp-joomla-1.6.3/openapp-joomla-passwd
+++ b/openapp-joomla-1.6.3/openapp-joomla-passwd
@@ -21,7 +21,7 @@ MD5_PWD=$(echo -n ${PASSWORD} | md5sum | cut -f 1 -d ' ')
 
 if [ -z `${QUERY} "SELECT username FROM jos_users WHERE username = 'admin'";` ]; then
     ${QUERY} "INSERT INTO jos_users (name, username, email, password, usertype, activation, params) VALUES ('Administrator', 'admin', 'your-email@email.com', '${MD5_PWD}', 'Super Administrator', '', '')" || fatal "Could not add user in jos_users"
-    SU_GROUP=$(${QUERY} "SELECT id FROM jos_usergroup WHERE title = 'Super Users'") || fatal "Could not fetch Super Users groupid"
+    SU_GROUP=$(${QUERY} "SELECT id FROM jos_usergroups WHERE title = 'Super Users'") || fatal "Could not fetch Super Users groupid"
     ADMIN_ID=$(${QUERY} "SELECT id FROM jos_users WHERE username = 'admin'") || fatal "Could not fetch adminusers userid"
     ${QUERY} "INSERT INTO jos_user_usergroup_map (user_id, group_id) VALUES (${ADMIN_ID}, ${SU_GROUP})" || fatal "Could not add admin to the Super Users group"
 else 
