Just depend on wget and don't test for curl.
Exit with exitcode 1 if the wget fails

diff --git a/debian/openapp-joomla-installer.postinst b/debian/openapp-joomla-installer.postinst
--- a/debian/openapp-joomla-installer.postinst
+++ b/debian/openapp-joomla-installer.postinst
@@ -39,8 +39,7 @@ install_joomla() {
 	rm -rf /var/www
 	mkdir /var/www
 
-	[ -x /usr/bin/wget ] && wget -q -O /tmp/joomla-$$.tar.gz ${MIRROR}/joomla-newest.tar.gz
-	[ -f /tmp/joomla-$$.tar.gz ] || /usr/bin/curl -s -o /tmp/joomla-$$.tar.gz ${MIRROR}/joomla-newest.tar.gz
+	wget -q -O /tmp/joomla-$$.tar.gz ${MIRROR}/joomla-newest.tar.gz
 	if [ $? -eq 0 ]; then
 		mkdir -p ${INSTALLDIR} || fatal "Unable to create directory ${INSTALLDIR}"
 		cd ${INSTALLDIR} || fatal "Unable to go into directory ${INSTALLDIR}"
@@ -58,7 +57,11 @@ install_joomla() {
                 [ $? -eq 0 ] || fatal "Unable to prepare ${INSTALLDIR}/configuration.php"
 		cat ${INSTALLDIR}/installation/sql/mysql/joomla.sql | sed -e 's/#__/jos_/g' | ${MYSQL} ${OPTS} joomla || fatal "Unable to add data to the database"
 		${MYSQL} ${OPTS} joomla -e "CREATE INDEX client_id ON jos_template_styles (client_id);"
+	else
+		echo "Failed to download Joomla from ${MIRROR}/joomla-newest.tar.gz"
+		exit 1
 	fi
+
 	echo "Fixing permissions on /var/www"
 	chown -R www-data:www-data /var/www
 	chmod 640 ${INSTALLDIR}/configuration.php
